---
- hosts: all
  remote_user: centos
  become: yes

  tasks:
    # install python3 and pymongo
    - name: install epel-release
      package:
        name: epel-release
        state: present

    - name: install python3 packages
      package:
        name:
          - python34
          - python34-pip
        state: present

    - name: get pip3 packages
      command: pip3 freeze
      register: freeze
      changed_when: false

    - name: pip3 install pymongo
      command: pip3 install pymongo
      when: "'pymongo' not in freeze.stdout"

    # configure tuned for necessary os tweaks
    - name: create tuned profile folder
      file:
        path: /etc/tuned/db-cluster
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: copy tuned profile
      copy:
        src: files/db-cluster_tuned.conf
        dest: /etc/tuned/db-cluster/tuned.conf
        owner: root
        group: root
        mode: 0644

    - name: get active tuned profile
      command: tuned-adm active
      register: profile
      changed_when: false

    - name: switch tuned profile
      command: tuned-adm profile db-cluster
      when: "'db-cluster' not in profile.stdout"

    # install mongo repo, package, systemd override and helper script
    - name: copy mongo helper script
      copy:
        src: files/mongo_init.py
        dest: /usr/local/bin/mongo_init
        owner: root
        group: root
        mode: 0755

    - name: copy mongodb-org repo
      copy:
        src: files/mongodb-org-4.0.repo
        dest: /etc/yum.repos.d/mongodb-org-4.0.repo
        owner: root
        group: root
        mode: 0644

    - name: install mongodb server package
      package:
        name: mongodb-org-server
        state: present

    # install custom selinux policy module
    # bug is fixed for selinux-policy-3.14.1-40.fc28.noarch
    # will probably take a while until backport
    - name: check for mongo_custom selinux policy
      command: semodule -l
      register: mongo_custom

    - name: copy mongo_custom selinux policy
      copy:
        src: files/mongo_custom.pp
        dest: /tmp/mongo_custom.pp
        owner: root
        group: root
        mode: 0644
      when: "'mongo_custom' not in mongo_custom.stdout"

    - name: install mongo_custom selinux policy
      command: semodule -i /tmp/mongo_custom.pp
      when: "'mongo_custom' not in mongo_custom.stdout"

    - name: create mongod systemd drop-in folder
      file:
        path: /etc/systemd/system/mongod.service.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: copy mongod systemd override
      copy:
        src: files/require_tuned.conf
        dest: /etc/systemd/system/mongod.service.d/require_tuned.conf
        owner: root
        group: root
        mode: 0644
      register: override

    - name: systemctl daemon-reload
      command: systemctl daemon-reload
      when: override.changed

    # deploy mongod config, start and enable the service
    - name: apply mongod configuration
      template:
        src: files/mongod.conf.j2
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: 0644
      register: mongodconf

    - name: restart mongod
      service:
        name: mongod
        state: restarted
        enabled: yes
      when:
        - mongodconf.changed

    - name: enable and start mongod service
      service:
        name: mongod
        state: started
        enabled: yes
